export const APP_TITLE = "Art Catalogue";
export const NO_RESULTS_FOUND = "No results found.";
export const SEARCH_BAR_PLACEHOLDER = "Type to search for artwork";
export const LOADING = "Loading";
export const ARTWORKS_TO_LOAD = 4;

export const MOCK_ARTWORKS = [
  {
    objectID: 1,
    isHighlight: false,
    accessionNumber: "1979.486.1",
    accessionYear: "1979",
    isPublicDomain: false,
    primaryImage: "",
    primaryImageSmall: "",
    additionalImages: [],
    constituents: [
      {
        constituentID: 164292,
        role: "Maker",
        name: "James Barton Longacre",
        constituentULAN_URL: "http://vocab.getty.edu/page/ulan/500011409",
        constituentWikidata_URL: "https://www.wikidata.org/wiki/Q3806459",
        gender: "",
      },
    ],
    department: "The American Wing",
    objectName: "Coin",
    title: "One-dollar Liberty Head Coin",
    culture: "",
    period: "",
    dynasty: "",
    reign: "",
    portfolio: "",
    artistRole: "Maker",
    artistPrefix: "",
    artistDisplayName: "James Barton Longacre",
    artistDisplayBio:
      "American, Delaware County, Pennsylvania 1794–1869 Philadelphia, Pennsylvania",
    artistSuffix: "",
    artistAlphaSort: "Longacre, James Barton",
    artistNationality: "American",
    artistBeginDate: "1794",
    artistEndDate: "1869",
    artistGender: "",
    artistWikidata_URL: "https://www.wikidata.org/wiki/Q3806459",
    artistULAN_URL: "http://vocab.getty.edu/page/ulan/500011409",
    objectDate: "1853",
    objectBeginDate: 1853,
    objectEndDate: 1853,
    medium: "Gold",
    dimensions: "Dimensions unavailable",
    measurements: null,
    creditLine: "Gift of Heinz L. Stoppelmann, 1979",
    geographyType: "",
    city: "",
    state: "",
    county: "",
    country: "",
    region: "",
    subregion: "",
    locale: "",
    locus: "",
    excavation: "",
    river: "",
    classification: "",
    rightsAndReproduction: "",
    linkResource: "",
    metadataDate: "2021-04-06T04:41:04.967Z",
    repository: "Metropolitan Museum of Art, New York, NY",
    objectURL: "https://www.metmuseum.org/art/collection/search/1",
    tags: null,
    objectWikidata_URL: "",
    isTimelineWork: false,
    GalleryNumber: "",
  },
  {
    objectID: 2,
    isHighlight: false,
    accessionNumber: "1980.264.5",
    accessionYear: "1980",
    isPublicDomain: false,
    primaryImage: "",
    primaryImageSmall: "",
    additionalImages: [],
    constituents: [
      {
        constituentID: 1079,
        role: "Maker",
        name: "Christian Gobrecht",
        constituentULAN_URL: "http://vocab.getty.edu/page/ulan/500077295",
        constituentWikidata_URL: "https://www.wikidata.org/wiki/Q5109648",
        gender: "",
      },
    ],
    department: "The American Wing",
    objectName: "Coin",
    title: "Ten-dollar Liberty Head Coin",
    culture: "",
    period: "",
    dynasty: "",
    reign: "",
    portfolio: "",
    artistRole: "Maker",
    artistPrefix: "",
    artistDisplayName: "Christian Gobrecht",
    artistDisplayBio: "1785–1844",
    artistSuffix: "",
    artistAlphaSort: "Gobrecht, Christian",
    artistNationality: "American",
    artistBeginDate: "1785",
    artistEndDate: "1844",
    artistGender: "",
    artistWikidata_URL: "https://www.wikidata.org/wiki/Q5109648",
    artistULAN_URL: "http://vocab.getty.edu/page/ulan/500077295",
    objectDate: "1901",
    objectBeginDate: 1901,
    objectEndDate: 1901,
    medium: "Gold",
    dimensions: "Dimensions unavailable",
    measurements: null,
    creditLine: "Gift of Heinz L. Stoppelmann, 1980",
    geographyType: "",
    city: "",
    state: "",
    county: "",
    country: "",
    region: "",
    subregion: "",
    locale: "",
    locus: "",
    excavation: "",
    river: "",
    classification: "",
    rightsAndReproduction: "",
    linkResource: "",
    metadataDate: "2021-04-06T04:41:04.967Z",
    repository: "Metropolitan Museum of Art, New York, NY",
    objectURL: "https://www.metmuseum.org/art/collection/search/2",
    tags: null,
    objectWikidata_URL: "",
    isTimelineWork: false,
    GalleryNumber: "",
  },
  {
    objectID: 1341,
    isHighlight: false,
    accessionNumber: "46.140.321",
    accessionYear: "1946",
    isPublicDomain: true,
    primaryImage:
      "https://images.metmuseum.org/CRDImages/ad/original/180308.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/180308.jpg",
    additionalImages: [],
    constituents: null,
    department: "The American Wing",
    objectName: "Candlestick",
    title: "Candlestick",
    culture: "American",
    period: "",
    dynasty: "",
    reign: "",
    portfolio: "",
    artistRole: "",
    artistPrefix: "",
    artistDisplayName: "",
    artistDisplayBio: "",
    artistSuffix: "",
    artistAlphaSort: "",
    artistNationality: "",
    artistBeginDate: "",
    artistEndDate: "",
    artistGender: "",
    artistWikidata_URL: "",
    artistULAN_URL: "",
    objectDate: "1875–1900",
    objectBeginDate: 1875,
    objectEndDate: 1900,
    medium: "Pressed colorless and opalescent glass",
    dimensions: "H. 6 1/2 in. (16.5 cm)",
    measurements: [
      {
        elementName: "Overall",
        elementDescription: null,
        elementMeasurements: { Height: 16.5 },
      },
    ],
    creditLine: "Gift of Mrs. Emily Winthrop Miles, 1946",
    geographyType: "Made in",
    city: "",
    state: "",
    county: "",
    country: "United States",
    region: "",
    subregion: "",
    locale: "",
    locus: "",
    excavation: "",
    river: "",
    classification: "",
    rightsAndReproduction: "",
    linkResource: "",
    metadataDate: "2022-02-09T04:42:08.947Z",
    repository: "Metropolitan Museum of Art, New York, NY",
    objectURL: "https://www.metmuseum.org/art/collection/search/1341",
    tags: [
      {
        term: "Dolphins",
        AAT_URL: "http://vocab.getty.edu/page/aat/300250159",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q7369",
      },
    ],
    objectWikidata_URL: "",
    isTimelineWork: false,
    GalleryNumber: "774",
  },
  {
    objectID: 13141,
    isHighlight: false,
    accessionNumber: "10.200",
    accessionYear: "1910",
    isPublicDomain: true,
    primaryImage:
      "https://images.metmuseum.org/CRDImages/ad/original/RRR Bust 10.200  Ret.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/RRR Bust 10.200  Ret.jpg",
    additionalImages: [],
    constituents: [
      {
        constituentID: 162686,
        role: "Artist",
        name: "John Quincy Adams Ward",
        constituentULAN_URL: "http://vocab.getty.edu/page/ulan/500023733",
        constituentWikidata_URL: "https://www.wikidata.org/wiki/Q2069921",
        gender: "",
      },
    ],
    department: "The American Wing",
    objectName: "Bust",
    title: "William Tilden Blodgett",
    culture: "American",
    period: "",
    dynasty: "",
    reign: "",
    portfolio: "",
    artistRole: "Artist",
    artistPrefix: "",
    artistDisplayName: "John Quincy Adams Ward",
    artistDisplayBio: "American, Urbana, Ohio 1830–1910 New York",
    artistSuffix: "",
    artistAlphaSort: "Ward, John Quincy Adams",
    artistNationality: "American",
    artistBeginDate: "1830",
    artistEndDate: "1910",
    artistGender: "",
    artistWikidata_URL: "https://www.wikidata.org/wiki/Q2069921",
    artistULAN_URL: "http://vocab.getty.edu/page/ulan/500023733",
    objectDate: "1865",
    objectBeginDate: 1865,
    objectEndDate: 1865,
    medium: "Marble",
    dimensions: "26 x 15 1/2 x 10 1/2 in. (66 x 39.4 x 26.7 cm)",
    measurements: [
      {
        elementName: "Overall",
        elementDescription: null,
        elementMeasurements: {
          Depth: 26.7,
          Height: 66,
          Weight: 48.98848,
          Width: 39.4,
        },
      },
    ],
    creditLine: "Gift of Mrs. John Quincy Adams Ward, 1910",
    geographyType: "",
    city: "",
    state: "",
    county: "",
    country: "",
    region: "",
    subregion: "",
    locale: "",
    locus: "",
    excavation: "",
    river: "",
    classification: "",
    rightsAndReproduction: "",
    linkResource: "",
    metadataDate: "2021-04-06T04:41:04.967Z",
    repository: "Metropolitan Museum of Art, New York, NY",
    objectURL: "https://www.metmuseum.org/art/collection/search/13141",
    tags: [
      {
        term: "Men",
        AAT_URL: "http://vocab.getty.edu/page/aat/300025928",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q8441",
      },
      {
        term: "Portraits",
        AAT_URL: "http://vocab.getty.edu/page/aat/300015637",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q134307",
      },
    ],
    objectWikidata_URL: "https://www.wikidata.org/wiki/Q20176828",
    isTimelineWork: true,
    GalleryNumber: "763",
  },
  {
    objectID: 13113,
    isHighlight: false,
    accessionNumber: "54.90.158",
    accessionYear: "1954",
    isPublicDomain: true,
    primaryImage:
      "https://images.metmuseum.org/CRDImages/ad/original/ap54.90.158.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/ap54.90.158.jpg",
    additionalImages: [
      "https://images.metmuseum.org/CRDImages/ad/original/APS2557.jpg",
      "https://images.metmuseum.org/CRDImages/ad/original/185390.jpg",
    ],
    constituents: [
      {
        constituentID: 162682,
        role: "Artist",
        name: "William Guy Wall",
        constituentULAN_URL: "http://vocab.getty.edu/page/ulan/500014016",
        constituentWikidata_URL: "https://www.wikidata.org/wiki/Q280662",
        gender: "",
      },
    ],
    department: "The American Wing",
    objectName: "Watercolor",
    title: "The Bay of New York Taken from Brooklyn Heights",
    culture: "American",
    period: "",
    dynasty: "",
    reign: "",
    portfolio: "",
    artistRole: "Artist",
    artistPrefix: "",
    artistDisplayName: "William Guy Wall",
    artistDisplayBio: "Irish, Dublin 1792–after 1864 Ireland (active America)",
    artistSuffix: "",
    artistAlphaSort: "Wall, William Guy",
    artistNationality: "Irish",
    artistBeginDate: "1792",
    artistEndDate: "1864",
    artistGender: "",
    artistWikidata_URL: "https://www.wikidata.org/wiki/Q280662",
    artistULAN_URL: "http://vocab.getty.edu/page/ulan/500014016",
    objectDate: "1820–25",
    objectBeginDate: 1820,
    objectEndDate: 1825,
    medium: "Watercolor on off-white wove paper",
    dimensions: "21 3/8 x 32 3/4 in. (54.3 x 83.2 cm)",
    measurements: [
      {
        elementName: "Overall",
        elementDescription: null,
        elementMeasurements: { Height: 54.3, Width: 83.1852 },
      },
      {
        elementName: "Mat",
        elementDescription: null,
        elementMeasurements: { Height: 76.20015, Width: 101.600204 },
      },
    ],
    creditLine:
      "The Edward W. C. Arnold Collection of New York Prints, Maps, and Pictures, Bequest of Edward W. C. Arnold, 1954",
    geographyType: "",
    city: "",
    state: "",
    county: "",
    country: "",
    region: "",
    subregion: "",
    locale: "",
    locus: "",
    excavation: "",
    river: "",
    classification: "",
    rightsAndReproduction: "",
    linkResource: "",
    metadataDate: "2021-09-16T04:35:47.213Z",
    repository: "Metropolitan Museum of Art, New York, NY",
    objectURL: "https://www.metmuseum.org/art/collection/search/13113",
    tags: [
      {
        term: "New York City",
        AAT_URL: "http://vocab.getty.edu/page/tgn/7007567",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q60",
      },
      {
        term: "Harbors",
        AAT_URL: "http://vocab.getty.edu/page/aat/300008678",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q283202",
      },
      {
        term: "Ships",
        AAT_URL: "http://vocab.getty.edu/page/aat/300082981",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q11446",
      },
    ],
    objectWikidata_URL: "",
    isTimelineWork: false,
    GalleryNumber: "",
  },
  {
    objectID: 13000,
    isHighlight: false,
    accessionNumber: "23.80.81",
    accessionYear: "1923",
    isPublicDomain: true,
    primaryImage:
      "https://images.metmuseum.org/CRDImages/ad/original/ap23.80.81.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/ap23.80.81.jpg",
    additionalImages: [],
    constituents: null,
    department: "The American Wing",
    objectName: "Painting",
    title: "Sarah Cornell Clarkson (Mrs. William Richmond)",
    culture: "American",
    period: "",
    dynasty: "",
    reign: "",
    portfolio: "",
    artistRole: "",
    artistPrefix: "",
    artistDisplayName: "",
    artistDisplayBio: "",
    artistSuffix: "",
    artistAlphaSort: "",
    artistNationality: "",
    artistBeginDate: "",
    artistEndDate: "",
    artistGender: "",
    artistWikidata_URL: "",
    artistULAN_URL: "",
    objectDate: "ca. 1830",
    objectBeginDate: 1827,
    objectEndDate: 1830,
    medium: "Oil on canvas",
    dimensions: "30 x 25 in. (76.2 x 63.5 cm)",
    measurements: [
      {
        elementName: "Overall",
        elementDescription: null,
        elementMeasurements: { Height: 76.2, Width: 63.5 },
      },
    ],
    creditLine: "Gift of Mr. and Mrs. William A. Moore, 1923",
    geographyType: "",
    city: "",
    state: "",
    county: "",
    country: "",
    region: "",
    subregion: "",
    locale: "",
    locus: "",
    excavation: "",
    river: "",
    classification: "",
    rightsAndReproduction: "",
    linkResource: "",
    metadataDate: "2021-04-06T04:41:04.967Z",
    repository: "Metropolitan Museum of Art, New York, NY",
    objectURL: "https://www.metmuseum.org/art/collection/search/13000",
    tags: [
      {
        term: "Portraits",
        AAT_URL: "http://vocab.getty.edu/page/aat/300015637",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q134307",
      },
      {
        term: "Women",
        AAT_URL: "http://vocab.getty.edu/page/aat/300025943",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q467",
      },
    ],
    objectWikidata_URL: "https://www.wikidata.org/wiki/Q20171698",
    isTimelineWork: false,
    GalleryNumber: "",
  },
  {
    objectID: 13001,
    isHighlight: false,
    accessionNumber: "1972.263.2",
    accessionYear: "1972",
    isPublicDomain: true,
    primaryImage:
      "https://images.metmuseum.org/CRDImages/ad/original/ap1972.263.2.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/ap1972.263.2.jpg",
    additionalImages: [],
    constituents: null,
    department: "The American Wing",
    objectName: "Painting",
    title: "Seascape Fantasy",
    culture: "American",
    period: "",
    dynasty: "",
    reign: "",
    portfolio: "",
    artistRole: "",
    artistPrefix: "",
    artistDisplayName: "",
    artistDisplayBio: "",
    artistSuffix: "",
    artistAlphaSort: "",
    artistNationality: "",
    artistBeginDate: "",
    artistEndDate: "",
    artistGender: "",
    artistWikidata_URL: "",
    artistULAN_URL: "",
    objectDate: "1770–1800",
    objectBeginDate: 1770,
    objectEndDate: 1800,
    medium: "Oil on wood",
    dimensions: "17 1/2 x 35 1/2 in. (43.7 x 89.4 cm)",
    measurements: [
      {
        elementName: "Framed",
        elementDescription: null,
        elementMeasurements: { Height: 62.9, Width: 108.6 },
      },
      {
        elementName: "Overall",
        elementDescription: null,
        elementMeasurements: { Height: 44.5, Width: 90.2 },
      },
    ],
    creditLine: "Gift of Edgar William and Bernice Chrysler Garbisch, 1972",
    geographyType: "",
    city: "",
    state: "",
    county: "",
    country: "",
    region: "",
    subregion: "",
    locale: "",
    locus: "",
    excavation: "",
    river: "",
    classification: "",
    rightsAndReproduction: "",
    linkResource: "",
    metadataDate: "2021-04-06T04:41:04.967Z",
    repository: "Metropolitan Museum of Art, New York, NY",
    objectURL: "https://www.metmuseum.org/art/collection/search/13001",
    tags: [
      {
        term: "Seascapes",
        AAT_URL: "http://vocab.getty.edu/page/aat/300117546",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q158607",
      },
      {
        term: "Boats",
        AAT_URL: "http://vocab.getty.edu/page/aat/300178749",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q35872",
      },
      {
        term: "Ships",
        AAT_URL: "http://vocab.getty.edu/page/aat/300082981",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q11446",
      },
    ],
    objectWikidata_URL: "https://www.wikidata.org/wiki/Q19924602",
    isTimelineWork: false,
    GalleryNumber: "774",
  },
];
